name: mts_visualizer
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  http: any
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter:
    sdk: flutter
  scidart: ^0.0.2-dev.12
  tabbed_view: ^1.13.0+1
  nice_buttons: ^0.0.2
  random_color: ^1.0.6-nullsafety
  rainbow_color: ^2.0.1
  file_picker: ^4.2.7

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
